<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>DVSeasons.Multiplayer</AssemblyName>
    <RootNamespace>DVSeasons.Multiplayer</RootNamespace>
    <Version>0.1.2</Version>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DVSeasons.Common\DVSeasons.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MultiplayerAPI"><HintPath>$(DVModsDir)\Multiplayer\MultiplayerAPI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(DVManagedDir)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityModManager"><HintPath>$(DVManagedDir)\UnityModManager\UnityModManager.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(DVManagedDir)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
