using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using UnityEngine.Profiling;
using UnityEngine.Rendering;
using Debug=UnityEngine.Debug;

namespace DVSeasons.AssetBundleBuild
{
    // Isolated throughput experiment, not an FPS model. The packed production
    // shader, height sampling, quality and output resolution are unchanged.
    // Unity 2019's public Recorder has CPU timestamps only, so timings below
    // explicitly include command submission and a GPU-completion readback.
    public static class SnowProceduralGpuVerification
    {
        const int Width=2560,Height=1440,Draws=32,Trials=7;
        enum Mode { Off, CopyOnly, Full }
        static readonly CultureInfo Invariant=CultureInfo.InvariantCulture;
        static string F(double value) {return value.ToString("F6",Invariant);}
        static void Require(bool condition,string message) {if(!condition)throw new Exception(message);}

        public static void Run()
        {
            int code=0;AssetBundle bundle=null;Material material=null;
            int oldVsync=QualitySettings.vSyncCount;
            try
            {
                QualitySettings.vSyncCount=0;
                string root=Path.GetFullPath(Path.Combine(Application.dataPath,"../.."));
                string runtime=Environment.GetEnvironmentVariable("DVSEASONS_VERIFY_MOD")??Path.Combine(root,"artifacts/build/DVSeasons");
                bundle=AssetBundle.LoadFromFile(Path.Combine(runtime,"AssetBundles/dvseasons_dv99"));
                Require(bundle!=null,"Packed snow AssetBundle unavailable");
                Shader shader=bundle.LoadAsset<Shader>("assets/dvseasons/dv99/shaders/proceduralsnow.shader");
                Require(shader!=null && shader.isSupported,"Packed ProceduralSnow shader unavailable/unsupported");
                material=new Material(shader);
                material.DisableKeyword("UNITY_SINGLE_PASS_STEREO");
                foreach(bool hdr in new[]{false,true})
                {
                    if(hdr)material.EnableKeyword("DVPS_FAST_HDR");else material.DisableKeyword("DVPS_FAST_HDR");
                    ShaderUtil.CompilePass(material,0,true);ShaderUtil.CompilePass(material,1,true);
                }
                Require(!ShaderUtil.ShaderHasError(shader),"Packed snow shader compilation failed");
                ReportTimingBackend();
                // Input patterns are generated by the existing semantic parity
                // fixture, then expanded into production-sized GPU resources.
                // All timed modes share exactly those resources and matrices.
                using(var inputs=new SnowProceduralCostVerification.Fixture(1,1,material))
                {
                    foreach(var scenario in new[]{
                        new SnowProceduralCostVerification.Scenario("near-ground") {Shelter=true},
                        new SnowProceduralCostVerification.Scenario("far-transition-rocks") {Center=896,Span=180,GradientX=1.2f,GradientZ=.3f,NormalY=.35f,Shelter=true},
                        new SnowProceduralCostVerification.Scenario("distant-rocks") {Center=1600,Span=450,GradientX=.7f,GradientZ=-.15f,NormalY=.6f,Shelter=true},
                        new SnowProceduralCostVerification.Scenario("vehicle-yard") {Vehicles=true,Shelter=true},
                        new SnowProceduralCostVerification.Scenario("sky-heavy") {Mixed=true,Sky=true,Shelter=true}})
                    {
                        inputs.Prepare(scenario);
                        using(var experiment=new Experiment(material,inputs))
                        {
                            foreach(bool hdr in new[]{true,false})
                            {
                                inputs.Configure(hdr,1f);
                                experiment.Configure(hdr);
                                experiment.VerifyOutputs(scenario.Name,hdr);
                                experiment.Measure(scenario.Name,hdr);
                            }
                        }
                    }
                }
                Debug.Log("SNOW_PROCEDURAL_GPU_EXPERIMENT_OK: packed shader pass0 at 2560x1440, HDR/LDR, five identical-input scenarios, off/copy/full A/B; unchanged 1024-square height maps and 256-square vehicle arrays; no production edits, no quality reduction, no per-pass GPU timestamp claim.");
            }
            catch(Exception error) {Debug.LogException(error);code=1;}
            finally
            {
                QualitySettings.vSyncCount=oldVsync;
                if(material!=null)UnityEngine.Object.DestroyImmediate(material);
                if(bundle!=null)bundle.Unload(true);
            }
            EditorApplication.Exit(code);
        }

        static void ReportTimingBackend()
        {
            bool gpuRecorder=typeof(Recorder).GetProperty("gpuElapsedNanoseconds",BindingFlags.Public|BindingFlags.Instance)!=null;
            bool profilerRecorder=typeof(Recorder).Assembly.GetType("Unity.Profiling.ProfilerRecorder")!=null;
            ulong frequency=0;
            try {frequency=FrameTimingManager.GetGpuTimerFrequency();}catch(Exception error) {Debug.Log("SNOW_GPU_TIMER_QUERY_UNAVAILABLE: "+error.GetType().Name);}
            Debug.Log("SNOW_GPU_TIMING_BACKEND: unity="+Application.unityVersion+" device="+SystemInfo.graphicsDeviceName+
                " API="+SystemInfo.graphicsDeviceType+" recorder_gpu_elapsed_api="+gpuRecorder+" profiler_recorder_api="+profilerRecorder+
                " frame_timing_gpu_frequency="+frequency+"; FrameTimingManager is whole-frame only; isolated-pass timestamps unavailable through the verified Unity2019 public Recorder; measurement=CPU_submission_plus_GPU_completion_readback");
        }

        sealed class Experiment:IDisposable
        {
            readonly Material material;
            readonly SnowProceduralCostVerification.Fixture inputs;
            readonly List<UnityEngine.Object> owned=new List<UnityEngine.Object>();
            readonly RenderTexture diffuse,specular,lighting,normal,depth,data,slope;
            readonly RenderTexture diffuseCopy,specularCopy,lightingCopy,aoCopy;
            readonly RenderTexture[] outputs=new RenderTexture[3];
            readonly RenderTargetIdentifier[] outputIds=new RenderTargetIdentifier[3];
            readonly CommandBuffer[] work=new CommandBuffer[3];
            readonly CommandBuffer initialize=new CommandBuffer {name="Snow GPU experiment identical target initialization"};
            readonly Mesh quad;
            readonly Texture2D fence,reader;
            readonly RenderTexture previous;
            bool hdr;

            T Keep<T>(T value) where T:UnityEngine.Object {owned.Add(value);return value;}
            RenderTexture Target(RenderTextureFormat format,int width=Width,int height=Height,int depthBits=0,FilterMode filter=FilterMode.Point)
            {
                Require(SystemInfo.SupportsRenderTextureFormat(format),"GPU experiment render format unsupported: "+format);
                var target=Keep(new RenderTexture(width,height,depthBits,format,RenderTextureReadWrite.Linear)
                    {filterMode=filter,wrapMode=TextureWrapMode.Clamp,useMipMap=false,autoGenerateMips=false,antiAliasing=1});
                Require(target.Create(),"GPU experiment could not allocate "+format);return target;
            }
            RenderTexture Expand(string input,RenderTextureFormat format)
            {
                Texture source=inputs.BoundTexture(input);Require(source!=null,"Missing synthetic shader input "+input);
                RenderTexture target=Target(format);Graphics.Blit(source,target);return target;
            }
            public Experiment(Material material,SnowProceduralCostVerification.Fixture inputs)
            {
                this.material=material;this.inputs=inputs;previous=RenderTexture.active;
                diffuse=Expand("_DVPSDiffuse",RenderTextureFormat.ARGB32);
                specular=Expand("_DVPSSpecular",RenderTextureFormat.ARGB32);
                lighting=Expand("_DVPSLighting",RenderTextureFormat.ARGBHalf);
                RenderTextureFormat normalFormat=SystemInfo.SupportsRenderTextureFormat(RenderTextureFormat.ARGB2101010)?RenderTextureFormat.ARGB2101010:RenderTextureFormat.ARGB32;
                normal=Expand("_DVPSNormal",normalFormat);depth=Expand("_CameraDepthTexture",RenderTextureFormat.RFloat);
                data=Expand("_DVPSVehicleData",RenderTextureFormat.ARGBHalf);slope=Expand("_DVPSVehicleSlope",RenderTextureFormat.R8);
                diffuseCopy=Target(RenderTextureFormat.ARGB32);specularCopy=Target(RenderTextureFormat.ARGB32);lightingCopy=Target(RenderTextureFormat.ARGBHalf);
                RenderTextureFormat aoFormat=SystemInfo.SupportsRenderTextureFormat(RenderTextureFormat.R8)?RenderTextureFormat.R8:RenderTextureFormat.ARGB32;
                aoCopy=Target(aoFormat,Width/2,Height/2,0,FilterMode.Bilinear);
                outputs[0]=Target(RenderTextureFormat.ARGB32,Width,Height,24);outputs[1]=Target(RenderTextureFormat.ARGB32);outputs[2]=Target(RenderTextureFormat.ARGBHalf);
                for(int i=0;i<3;i++)outputIds[i]=new RenderTargetIdentifier(outputs[i]);
                initialize.Blit(diffuse,outputs[0]);initialize.Blit(specular,outputs[1]);initialize.Blit(lighting,outputs[2]);
                quad=Keep(new Mesh {vertices=new[]{new Vector3(-1,-1,0),new Vector3(1,-1,0),new Vector3(1,1,0),new Vector3(-1,1,0)},
                    uv=new[]{Vector2.zero,Vector2.right,Vector2.one,Vector2.up},triangles=new[]{0,1,2,0,2,3}});
                reader=Keep(new Texture2D(Width,Height,TextureFormat.RGBA32,false,true));
                fence=Keep(new Texture2D(1,1,TextureFormat.RGBAFloat,false,true));
                material.SetTexture("_DVPSNormal",normal);material.SetTexture("_CameraDepthTexture",depth);
                material.SetTexture("_DVPSVehicleData",data);material.SetTexture("_DVPSVehicleSlope",slope);
                Debug.Log("SNOW_GPU_RESOURCES: output=2560x1440 MRT=ARGB32/ARGB32/ARGBHalf normal="+normalFormat+
                    " depth=RFloat vehicle_data=ARGBHalf vehicle_slope=R8 AO="+aoFormat+"@1280x720; native-sized GPU inputs, deterministic upscaled parity patterns, three sampled vehicle slots, no scene/vehicle/exposure capture in this experiment");
            }

            public void Configure(bool highDynamicRange)
            {
                hdr=highDynamicRange;
                material.SetInt("_SnowSrcBlend",(int)(hdr?BlendMode.SrcAlpha:BlendMode.One));
                material.SetInt("_SnowDstBlend",(int)(hdr?BlendMode.OneMinusSrcAlpha:BlendMode.Zero));
                material.SetInt("_SnowAlphaSrcBlend",(int)(hdr?BlendMode.Zero:BlendMode.One));
                material.SetInt("_SnowAlphaDstBlend",(int)(hdr?BlendMode.One:BlendMode.Zero));
                material.SetInt("_SnowSpecAlphaDstBlend",(int)(hdr?BlendMode.OneMinusSrcAlpha:BlendMode.Zero));
                material.SetTexture("_DVPSDiffuse",hdr?aoCopy:diffuseCopy);
                material.SetTexture("_DVPSSpecular",specularCopy);material.SetTexture("_DVPSLighting",lightingCopy);
                for(int i=0;i<work.Length;i++)
                {
                    if(work[i]!=null)work[i].Dispose();
                    work[i]=Record((Mode)i,Draws);
                }
            }

            CommandBuffer Record(Mode mode,int count)
            {
                var commands=new CommandBuffer {name="Snow isolated fullscreen "+mode};
                for(int i=0;i<count;i++)
                {
                    if(mode!=Mode.Off)
                    {
                        commands.BeginSample("Snow experiment buffer copies");
                        if(hdr)commands.Blit(diffuse,aoCopy,material,1);
                        else {commands.Blit(diffuse,diffuseCopy);commands.Blit(specular,specularCopy);commands.Blit(lighting,lightingCopy);}
                        commands.EndSample("Snow experiment buffer copies");
                    }
                    commands.SetRenderTarget(outputIds,outputs[0]);
                    if(mode==Mode.Full)
                    {
                        commands.BeginSample("Snow experiment production shading");
                        commands.DrawMesh(quad,Matrix4x4.identity,material,0,0);
                        commands.EndSample("Snow experiment production shading");
                    }
                }
                return commands;
            }

            void Fence()
            {
                RenderTexture.active=outputs[0];fence.ReadPixels(new Rect(0,0,1,1),0,0,false);
            }
            void Initialize()
            {Graphics.ExecuteCommandBuffer(initialize);Fence();}
            double Time(Mode mode)
            {
                // Identical target contents and drained setup precede each run.
                // Recording, texture generation and resource creation are excluded.
                Initialize();var watch=Stopwatch.StartNew();Graphics.ExecuteCommandBuffer(work[(int)mode]);Fence();watch.Stop();
                return watch.Elapsed.TotalMilliseconds/Draws;
            }
            ulong[] Snapshot(Mode mode)
            {
                Initialize();using(var single=Record(mode,1))Graphics.ExecuteCommandBuffer(single);
                var result=new ulong[outputs.Length];
                for(int target=0;target<outputs.Length;target++)
                {
                    RenderTexture.active=outputs[target];reader.ReadPixels(new Rect(0,0,Width,Height),0,0,false);
                    Color32[] pixels=reader.GetPixels32();ulong hash=1469598103934665603UL;
                    for(int i=0;i<pixels.Length;i++)
                    {
                        Color32 pixel=pixels[i];uint packed=(uint)(pixel.r|pixel.g<<8|pixel.b<<16|pixel.a<<24);
                        hash=unchecked((hash^packed)*1099511628211UL);
                    }
                    result[target]=hash;
                }
                return result;
            }
            public void VerifyOutputs(string scenario,bool highDynamicRange)
            {
                ulong[] off=Snapshot(Mode.Off),copy=Snapshot(Mode.CopyOnly),full=Snapshot(Mode.Full),repeat=Snapshot(Mode.Full);
                bool changed=false;
                for(int i=0;i<3;i++)
                {
                    Require(off[i]==copy[i],"Copy-only baseline changed MRT output "+i+" case="+scenario);
                    Require(full[i]==repeat[i],"Identical snow input produced unstable output "+i+" case="+scenario);
                    changed|=full[i]!=off[i];
                }
                Require(changed,"Full snow pass did not write visible output: "+scenario+" HDR="+highDynamicRange);
                Debug.Log("SNOW_GPU_INPUT_OUTPUT_OK: case="+scenario+" hdr="+highDynamicRange+" copy_equals_off=true full_changes_output=true identical_full_repeat=true verification=full_resolution_RGBA8_hashes_not_float_parity");
            }
            public void Measure(string scenario,bool highDynamicRange)
            {
                // Dispose managed full-resolution verification arrays before
                // warming/timing, so readback validation cannot trigger their
                // collection in the middle of an otherwise allocation-light run.
                GC.Collect();GC.WaitForPendingFinalizers();GC.Collect();
                for(int i=0;i<2;i++)for(int mode=0;mode<3;mode++)Time((Mode)mode);
                var samples=new[]{new List<double>(),new List<double>(),new List<double>()};
                var shading=new List<double>();var total=new List<double>();
                for(int trial=0;trial<Trials;trial++)
                {
                    var measured=new double[3];
                    for(int order=0;order<3;order++)
                    {
                        int mode=(trial%2==0?(order+trial)%3:(2-order+trial)%3);
                        measured[mode]=Time((Mode)mode);samples[mode].Add(measured[mode]);
                    }
                    shading.Add(measured[(int)Mode.Full]-measured[(int)Mode.CopyOnly]);
                    total.Add(measured[(int)Mode.Full]-measured[(int)Mode.Off]);
                    Debug.Log("SNOW_GPU_AB_TRIAL: case="+scenario+" hdr="+highDynamicRange+" trial="+trial+
                        " off_ms="+F(measured[0])+" copy_ms="+F(measured[1])+" full_ms="+F(measured[2])+" full_minus_copy_ms="+F(shading[trial]));
                }
                foreach(var values in samples)values.Sort();shading.Sort();total.Sort();
                Debug.Log("SNOW_PROCEDURAL_1440P_AB: case="+scenario+" hdr="+highDynamicRange+" resolution=2560x1440 draws_per_batch="+Draws+
                    " alternating_trials="+Trials+" off_median_ms="+F(samples[0][Trials/2])+" copy_median_ms="+F(samples[1][Trials/2])+
                    " full_median_ms="+F(samples[2][Trials/2])+" paired_full_minus_copy_median_ms="+F(shading[Trials/2])+
                    " paired_full_minus_off_median_ms="+F(total[Trials/2])+" shading_delta_range_ms="+F(shading[0])+".."+F(shading[Trials-1])+
                    " measurement=pre_recorded_CPU_submission_plus_GPU_completion_readback normalized_per_pass=true pure_GPU_timestamp=false not_game_FPS=true");
            }
            public void Dispose()
            {
                RenderTexture.active=previous;
                initialize.Dispose();foreach(var commands in work)if(commands!=null)commands.Dispose();
                foreach(var resource in owned)if(resource!=null)UnityEngine.Object.DestroyImmediate(resource);
            }
        }
    }
}
